# Generated by Django 5.2.7 on 2026-02-25 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('background_video', models.FileField(upload_to='hero_videos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='NGO', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('about_short', models.TextField(blank=True)),
                ('copyright', models.CharField(blank=True, max_length=300)),
                ('nav_color', models.CharField(blank=True, max_length=300)),
                ('text_color', models.CharField(blank=True, max_length=300)),
                ('partners_banner', models.ImageField(blank=True, null=True, upload_to='partners_banner/')),
                ('about_banner', models.ImageField(blank=True, null=True, upload_to='about_banner/')),
                ('contect_banner', models.ImageField(blank=True, null=True, upload_to='contect_banner/')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('googlemap', models.TextField(blank=True, null=True)),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='payment/')),
                ('default_hero', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('default_cta_text', models.CharField(blank=True, max_length=200)),
                ('default_cta_link', models.CharField(blank=True, max_length=300)),
                ('youtube', models.URLField(blank=True, max_length=500)),
                ('instagram', models.URLField(blank=True, max_length=500)),
                ('linkdin', models.URLField(blank=True, max_length=500)),
                ('facebook', models.URLField(blank=True, max_length=500)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='WhyJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='home.herosection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
