# Generated by Django 5.2.7 on 2026-02-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='about_short',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='default_cta_link',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='default_cta_text',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='default_hero',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='maintenance_mode',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='partners_banner',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='payment_qr',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(max_length=200),
        ),
    ]
