# Generated by Django 5.2.7 on 2026-02-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_talentcategory_alter_sitesetting_options_talent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talent',
            new_name='OurArties',
        ),
    ]
