# Generated by Django 5.2.7 on 2026-02-26 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_talent_ourarties'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='the_journey_background_video',
            field=models.FileField(blank=True, null=True, upload_to='the_journey_background_video/'),
        ),
        migrations.AlterField(
            model_name='ourarties',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Arties', to='home.talentcategory'),
        ),
    ]
