# Generated by Django 5.2.7 on 2026-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_whychoosesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whychoosesection',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
