# Generated by Django 5.2.7 on 2026-02-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_workingcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='working_profile/')),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='home.workingcategory')),
            ],
            options={
                'verbose_name': 'Working Profile',
                'verbose_name_plural': 'Working Profiles',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
