# Generated by Django 5.2.7 on 2026-02-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, upload_to='working_category/'),
        ),
    ]
